version: "3"
services:
  lock-manager:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
    environment:
      - NODE_ID=lock-manager
    ports:
      - "8081:8080"
    command: ["python", "-m", "src.nodes.lock_manager"]

  queue-node:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
    environment:
      - NODE_ID=queue-node
    ports:
      - "8082:8080"
    command: ["python", "-m", "src.nodes.queue_node"]

  cache-node:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
    environment:
      - NODE_ID=cache-node
    ports:
      - "8083:8080"
    command: ["python", "-m", "src.nodes.cache_node"]
